# Pipeline CI para TP4 DevOps
# Configurado para ejecutarse en un agente Self-Hosted

trigger:
- main

pool:
  name: 'LocalPool' 

stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
  - job: BuildFrontend
    displayName: 'Build Frontend'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Instalar Node.js'

    - script: |
        cd front
        npm ci
      displayName: 'Instalar dependencias del frontend'

    - script: |
        cd front
        npm run build
      displayName: 'Build frontend'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/front/build'
        artifact: 'frontend-build'
        publishLocation: 'pipeline'
      displayName: 'Publicar artefactos del frontend'

  - job: BuildBackend
    displayName: 'Build Backend'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Instalar Node.js'

    - script: |
        cd back
        npm ci
      displayName: 'Instalar dependencias del backend'

    - script: |
        cd back
        npm test
      displayName: 'Ejecutar tests del backend'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/back'
        artifact: 'backend-build'
        publishLocation: 'pipeline'
      displayName: 'Publicar artefactos del backend'