# Pipeline CI para TP4 DevOps
# Configurado para ejecutarse en un agente Self-Hosted

trigger:
  - main

pool:
  name: 'SelfHosted'

stages:
- stage: CI
  jobs:
  - job: BuildBackend
    steps:
    - task: NodeJS@1
      inputs:
        versionSpec: '16.x'
    - script: |
        cd back
        npm ci
        npm test
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'back'
        artifact: 'backend-dist'

  - job: BuildFrontend
    steps:
    - task: NodeJS@1
      inputs:
        versionSpec: '16.x'
    - script: |
        cd front
        npm ci
        npm run build
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'front/build'
        artifact: 'frontend-dist'